name: Slack Notification

on:
  pull_request:
    types: [opened, reopened, ready_for_review, closed]
  issues:
    types: [opened, reopened, closed]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/slack-integration@beta
        with:
          slack-token: ${{ secrets.SLACK_APP_TOKEN }}
          channel: 'intern_k_yokoyama_github'
          subscribe-pulls: true
          subscribe-issues: true
          subscribe-reviews: true
          subscribe-pull-comments: true
          subscribe-issue-comments: true
          threading-comments: true
